<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12266" started-at="2018-06-21T03:51:59Z" finished-at="2018-06-21T03:52:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12266" started-at="2018-06-21T03:51:59Z" finished-at="2018-06-21T03:52:11Z">
      <class name="testNG.WrongCredentialsTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:testNG.WrongCredentialsTest@57fffcd7]" name="setup" is-config="true" duration-ms="4363" started-at="2018-06-21T03:51:59Z" finished-at="2018-06-21T03:52:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testNG.WrongCredentialsTest@57fffcd7]" name="beforeMethod" is-config="true" duration-ms="1001" started-at="2018-06-21T03:52:03Z" finished-at="2018-06-21T03:52:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="AnemailAddressRequired()[pri:0, instance:testNG.WrongCredentialsTest@57fffcd7]" name="AnemailAddressRequired" duration-ms="774" started-at="2018-06-21T03:52:04Z" finished-at="2018-06-21T03:52:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AnemailAddressRequired -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testNG.WrongCredentialsTest@57fffcd7]" name="beforeMethod" is-config="true" duration-ms="1127" started-at="2018-06-21T03:52:05Z" finished-at="2018-06-21T03:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="InvalidEmailAddress()[pri:0, instance:testNG.WrongCredentialsTest@57fffcd7]" name="InvalidEmailAddress" duration-ms="823" started-at="2018-06-21T03:52:06Z" finished-at="2018-06-21T03:52:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testNG.WrongCredentialsTest.InvalidEmailAddress(WrongCredentialsTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidEmailAddress -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testNG.WrongCredentialsTest@57fffcd7]" name="beforeMethod" is-config="true" duration-ms="1390" started-at="2018-06-21T03:52:07Z" finished-at="2018-06-21T03:52:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="PasswordIsRequired()[pri:0, instance:testNG.WrongCredentialsTest@57fffcd7]" name="PasswordIsRequired" duration-ms="595" started-at="2018-06-21T03:52:08Z" finished-at="2018-06-21T03:52:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PasswordIsRequired -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testNG.WrongCredentialsTest@57fffcd7]" name="beforeMethod" is-config="true" duration-ms="1262" started-at="2018-06-21T03:52:09Z" finished-at="2018-06-21T03:52:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="wrongCredentialsTest()[pri:0, instance:testNG.WrongCredentialsTest@57fffcd7]" name="wrongCredentialsTest" duration-ms="914" started-at="2018-06-21T03:52:10Z" finished-at="2018-06-21T03:52:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongCredentialsTest -->
      </class> <!-- testNG.WrongCredentialsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
